---
index: main.html
location: 'http://localhost:3000/'
log:
  log_level: 'INFO'
  file:
    autoflush: 1
    filename: 'fashionista.log'
    mode: 'append'
    pattern: '[%d] [%p] %m%n'
  screen:
    stderr: 1
    utf8: 1
