version: 2

jobs:
  build_and_test:
    docker:
      - image: circleci/node:10.16.0-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bin/install

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: run tests
          command: |
            npm run test

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
