"use strict";

exports.__esModule = true;
exports.NUM_COLUMNS = exports.GUTTER = exports.CONTAINER_PADDING_THIN = exports.CONTAINER_PADDING = exports.CONTAINER_MAX_WIDTH = void 0;
const NUM_COLUMNS = 12;
exports.NUM_COLUMNS = NUM_COLUMNS;
const CONTAINER_MAX_WIDTH = 1440;
exports.CONTAINER_MAX_WIDTH = CONTAINER_MAX_WIDTH;
const GUTTER = 20;
exports.GUTTER = GUTTER;
const CONTAINER_PADDING_THIN = 20;
exports.CONTAINER_PADDING_THIN = CONTAINER_PADDING_THIN;
const CONTAINER_PADDING = 40;
exports.CONTAINER_PADDING = CONTAINER_PADDING;