"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.CONTAINER_PADDING = exports.CONTAINER_PADDING_THIN = exports.GUTTER = exports.CONTAINER_MAX_WIDTH = exports.NUM_COLUMNS = void 0;
var NUM_COLUMNS = 12;
exports.NUM_COLUMNS = NUM_COLUMNS;
var CONTAINER_MAX_WIDTH = 1440;
exports.CONTAINER_MAX_WIDTH = CONTAINER_MAX_WIDTH;
var GUTTER = 20;
exports.GUTTER = GUTTER;
var CONTAINER_PADDING_THIN = 20;
exports.CONTAINER_PADDING_THIN = CONTAINER_PADDING_THIN;
var CONTAINER_PADDING = 40;
exports.CONTAINER_PADDING = CONTAINER_PADDING;