import styled from 'styled-components';
import COLORS from '../../../constants/colors-config';
import { pxToRem, stepToRem } from '../../../helpers/utils/typography';
import TYPOGRAPHY from '../../../constants/typography-config';
import { hexToRgba as rgba } from '../../../helpers/utils/hex-to-rgba';
import { ScreenConfig } from '../../../constants/screen-config';
export var Styles = styled.div.withConfig({
  displayName: "styles__Styles",
  componentId: "sc-1eo5kcj-0"
})(["position:relative;&.SingleEntryTable--isSliding .SingleEntryTable__TableContainer{overflow-x:scroll;margin-bottom:", ";border-left:", " solid ", ";border-right:", " solid ", ";background:linear-gradient( to right,white 30%,", " ),linear-gradient(to left,white 30%,", "),radial-gradient( farthest-side at 0 50%,", ",", " ),radial-gradient( farthest-side at 100% 50%,", ",", " );background-repeat:no-repeat;background-size:", " 100%,", " 100%,", " 100%,", " 100%;background-position:0,100%;background-attachment:local,local,scroll,scroll;@media screen and (min-width:0\0){background:", ";}@media (min-width:", "){background-position:0,100%;}}.SingleEntryTable__Table{width:100%;border-spacing:0;table-layout:fixed;border-collapse:separate;@media screen and (min-width:0\0){border-collapse:collapse;}}.SingleEntryTable__Column{height:", ";padding:", ";border:", " solid rgba(0,0,0,0.067);font-size:", ";line-height:1.3;box-sizing:border-box;text-align:left;vertical-align:middle;&.SingleEntryTable__Column--Col{", " border-left-width:0;border-top-width:0;&:first-child{border-left-width:", ";}}&.SingleEntryTable__Column--HeaderCol{", " background:", ";border-left-width:0;&:first-child{border-color:", ";border-left-width:", ";}}}"], pxToRem(30), pxToRem(2), rgba(COLORS.background1, 0.0667), pxToRem(2), rgba(COLORS.background1, 0.0667), rgba(COLORS.background1, 0), rgba(COLORS.background1, 0), rgba(COLORS.font1, 0.2), rgba(COLORS.font1, 0), rgba(COLORS.font1, 0.2), rgba(COLORS.font1, 0), pxToRem(40), pxToRem(40), pxToRem(14), pxToRem(14), COLORS.background1, pxToRem(ScreenConfig.M.min), pxToRem(68), pxToRem(20), pxToRem(2), stepToRem(-1), TYPOGRAPHY.fontStyles.light, pxToRem(2), TYPOGRAPHY.fontStyles.bold, COLORS.background2, COLORS.line1, pxToRem(2));