# Procfile for development with hot reloading of JavaScript and CSS

# Server
rails: REACT_ON_RAILS_ENV=HOT rails s -p 3003 -b 0.0.0.0

# Run the hot reload server for client development
hot-assets: yarn hot-assets

# Keep the JS fresh for server rendering.
rails-server-assets: yarn build:dev
