export var NUM_COLUMNS = 12;
export var CONTAINER_MAX_WIDTH = 1440;
export var GUTTER = 20;
export var CONTAINER_PADDING_THIN = 20;
export var CONTAINER_PADDING = 40; // Please don't use CONTAINER_PADDING_MOBILE.
// Use CONTAINER_PADDING_THIN instead.

export var CONTAINER_PADDING_MOBILE = CONTAINER_PADDING_THIN;